version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://werewolf_user:werewolf_password@db:5432/werewolf_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        target: /app/node_modules
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: npm run dev
    networks:
      - werewolf-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: werewolf_db
      POSTGRES_USER: werewolf_user
      POSTGRES_PASSWORD: werewolf_password
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - werewolf-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U werewolf_user -d werewolf_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - werewolf-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  werewolf-network:
    driver: bridge